### ISSUE TITLE
HttpClient do not detect header params

### ISSUE THREAD

**Issue by JayendharPrakash** [angular/common-builds#1]
We used both Http & HttpClient to fetch the header params. Http returns the header, but HttpClient doesn't.

```
constructor(private http: Http, private httpClient: HttpClient) {}
getContent() {
        const url = '';
        return this.http.post(url, data)
            .map((res: HttpResponse<any>) => {
                console.log('http content', res);
            });


        return this.httpClient.post(url, data, { observe: 'response' })
            .map((res: HttpResponse<any>) => {
                console.log('httpClient content',res);
            });
}
```

When checked in console, http returns the response with headers but httpClient returns an empty array.

When checked in networks tab of browser inspector, it displays all the header parameters. 

The server accepts the following CORS options:
  origin: '*',
  methods: 'GET,HEAD,PUT,PATCH,POST,DELETE',
  allowedHeaders: 'Origin,X-Requested-With,x-access-token,Content-Type,Authorization,Accept,jwt',
  exposedHeaders: 'Content-Type,Authorization,jwt'

Please help us figure out how to fetch the headers using httpClient.

Thanks in advance.

**Comment by ocombe** [comment]
Hello, the sources for this package are in the main [Angular repo](https://github.com/angular/angular). Please file issues and pull requests against that repo.
